#-*-coding: utf-8 -*-
from sikuli import *

def coluna_residencial():
    wait(3)
    click(Pattern("1535053502551.png").similar(0.82))
    wait(3)
    click(Pattern("1535053502551.png").similar(0.82))
    wait(2)
    type(Key.TAB)
    type(Key.TAB)
    wait(2)
    type(Key.DOWN)
    wait(2)
    # Push down keys.
    keyDown(Key.CTRL)
    keyDown(Key.SHIFT)
    type(Key.DOWN)
    type(Key.DOWN)
    type(Key.DOWN)
    type(Key.DOWN)
    type(Key.DOWN)
    type(Key.DOWN)
    type(Key.DOWN)
    # Release keys. 
    keyUp()
    wait(2)
    type("c",KEY_CTRL)
    click("1535056088259.png")
    wait(2)
    click("1535131326140.png")
    wait(2)
    click("1535055385625.png")
    type(Key.TAB)
    wait(2)
    type(Key.TAB)
    wait(2)
    type(Key.DOWN)
    type("v",KEY_CTRL)
    wait(2)
    click("1535117379745.png")
    type(Key.UP)
    print("Residencial pronto")
    
def coluna_comercial():
    wait(3)
    click(Pattern("1535117222792.png").similar(0.98))
    wait(2)
    type(Key.TAB)
    type(Key.TAB)
    wait(2)
    type(Key.DOWN)
    wait(2)
    # Push down keys.
    keyDown(Key.CTRL)
    keyDown(Key.SHIFT)
    type(Key.DOWN)
    type(Key.DOWN)
    type(Key.DOWN)
    type(Key.DOWN)
    type(Key.DOWN)
    type(Key.DOWN)
    type(Key.DOWN)
    # Release keys. 
    keyUp()
    wait(2)
    type("c",KEY_CTRL)
    click("1535056088259.png")
    wait(2)
    click(Pattern("1535637275144.png").targetOffset(5,-18))
    type(Key.TAB)
    wait(2)
    type(Key.TAB)
    wait(2)
    type(Key.DOWN)
    type("v",KEY_CTRL)
    wait(2)
    click("1535117379745.png")
    type(Key.UP)
    print("Comercial pronto")

def coluna_industrial():
    wait(3)
    click("1535117562683.png")
    wait(2)
    type(Key.TAB)
    type(Key.TAB)
    wait(2)
    type(Key.DOWN)
    wait(2)
    # Push down keys.
    keyDown(Key.CTRL)
    keyDown(Key.SHIFT)
    type(Key.DOWN)
    type(Key.DOWN)
    type(Key.DOWN)
    type(Key.DOWN)
    type(Key.DOWN)
    type(Key.DOWN)
    type(Key.DOWN)
    # Release keys. 
    keyUp()
    wait(2)
    type("c",KEY_CTRL)
    click("1535056088259.png")
    wait(2)
    click("1535117589931.png")
    type(Key.TAB)
    wait(2)
    type(Key.TAB)
    wait(2)
    type(Key.DOWN)
    type("v",KEY_CTRL)
    wait(2)
    click("1535117379745.png")
    type(Key.UP)
    print("Industrial pronto")

   
def main():
    coluna_residencial()
    coluna_comercial()
    coluna_industrial()
    
    
if __name__ == "__main__":
    main() 